version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mypet
    volumes:
      - dbmypet:/var/lib/mysql
    ports:
      - 3309:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8086:80
    environment:
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass
    depends_on:
      - db
volumes:
  dbmypet: